# based on https://github.com/MiyooCFW/gmenunx/blob/master/.github/workflows/c-cpp.yml
name: CI Build

on:
  push:
  pull_request:
  workflow_call:
    inputs:
      submodule:
        description: The directory of the submodule, if this workflow is being called on a submodule
        required: true
        type: string

jobs:   
  build:
    runs-on: ubuntu-20.04
    container:
      image: miyoocfw/toolchain:latest
    steps:
    - run: echo "submodule ${{ inputs.submodule }} on ${{ github.event }}"
    - uses: actions/checkout@v3
    - if: inputs.submodule
      run: git submodule update --init --depth 1 -- ${{ inputs.submodule }}
    - name: build
      run: cd ${{ inputs.submodule || '.' }} && make
    - uses: actions/upload-artifact@v3
      with:
        name: miyooctl-musl
        path: ${{ inputs.submodule || '.' }}/miyooctl
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`
