# based on https://github.com/MiyooCFW/gmenunx/blob/master/.github/workflows/c-cpp.yml
name: Legacy CI Build

on: [push, pull_request, workflow_call]

jobs:   
  build-legacy:
    name: miyooctl (uClibc)
    runs-on: ubuntu-20.04
    container:
      image: nfriedly/miyoo-toolchain:steward
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: make
    - uses: actions/upload-artifact@v3
      with:
        name: miyooctl legacy binary
        path: miyooctl
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`
